using Npgsql;

namespace PadelMatch.Api.Tests.TestSupport;

public sealed class EphemeralDatabase : IAsyncLifetime
{
    private readonly string adminConnectionString;

    public string DatabaseName { get; } = $"padelmatch_test_{Guid.NewGuid():N}";
    public string ConnectionString { get; }

    public EphemeralDatabase()
    {
        var connection = new NpgsqlConnectionStringBuilder(
            Environment.GetEnvironmentVariable("PADELMATCH_TEST_CONNECTION") ??
            "Host=localhost;Port=5432;Database=postgres;Username=padelmatch;Password=padelmatch_local_only;Timeout=5");
        connection.Database = "postgres";
        adminConnectionString = connection.ConnectionString;
        connection.Database = DatabaseName;
        ConnectionString = connection.ConnectionString;
    }

    public async Task InitializeAsync()
    {
        await using var connection = new NpgsqlConnection(adminConnectionString);
        await connection.OpenAsync();
        await using var command = new NpgsqlCommand($"CREATE DATABASE \"{DatabaseName}\"", connection);
        await command.ExecuteNonQueryAsync();
    }

    public async Task DisposeAsync()
    {
        await using var connection = new NpgsqlConnection(adminConnectionString);
        await connection.OpenAsync();
        // The name is generated by this fixture; never use a caller-supplied database name here.
        await using var command = new NpgsqlCommand($"DROP DATABASE IF EXISTS \"{DatabaseName}\" WITH (FORCE)", connection);
        await command.ExecuteNonQueryAsync();
    }
}
