using Npgsql;

namespace PadelMatch.Api.Tests.TestSupport;

public sealed class EphemeralDatabase : IAsyncLifetime
{
    private const int MaxDropAttempts = 10;

    private readonly string adminConnectionString;

    public string DatabaseName { get; } = $"padelmatch_test_{Guid.NewGuid():N}";
    public string ConnectionString { get; }

    public EphemeralDatabase()
    {
        var connection = new NpgsqlConnectionStringBuilder(
            Environment.GetEnvironmentVariable("PADELMATCH_TEST_CONNECTION") ??
            "Host=localhost;Port=5432;Database=postgres;Username=padelmatch;Password=padelmatch_local_only;Timeout=5")
        {
            // Many test classes create, migrate and drop databases at once; the 5 s connect timeout used by the app
            // isn't enough under that load.
            Timeout = 30
        };
        connection.Database = "postgres";
        adminConnectionString = connection.ConnectionString;
        connection.Database = DatabaseName;
        ConnectionString = connection.ConnectionString;
    }

    public async Task InitializeAsync()
    {
        await using var connection = new NpgsqlConnection(adminConnectionString);
        await connection.OpenAsync();
        await using var command = new NpgsqlCommand($"CREATE DATABASE \"{DatabaseName}\"", connection);
        await command.ExecuteNonQueryAsync();
    }

    public async Task DisposeAsync()
    {
        // Close the idle pooled connections the app under test left open on this database, so a plain DROP can go
        // through. DROP ... WITH (FORCE) used to fail intermittently with 42501: it tries to terminate every backend
        // on the database, including PostgreSQL's own (e.g. an autovacuum worker), which this role may not signal.
        // A plain DROP handles those itself and only needs our own connections gone.
        await using (var pooled = new NpgsqlConnection(ConnectionString))
        {
            NpgsqlConnection.ClearPool(pooled);
        }

        await using var connection = new NpgsqlConnection(adminConnectionString);
        await connection.OpenAsync();
        // The name is generated by this fixture; never use a caller-supplied database name here.
        for (var attempt = 1; ; attempt++)
        {
            var force = attempt == MaxDropAttempts ? " WITH (FORCE)" : string.Empty;
            await using var command = new NpgsqlCommand($"DROP DATABASE IF EXISTS \"{DatabaseName}\"{force}", connection);
            try
            {
                await command.ExecuteNonQueryAsync();
                return;
            }
            catch (PostgresException ex) when (ex.SqlState == PostgresErrorCodes.ObjectInUse && attempt < MaxDropAttempts)
            {
                // A connection is still closing; give it a moment.
                await Task.Delay(100 * attempt);
            }
        }
    }
}
